import = ["/home/ammar/.config/alacritty/gruvbox_dark.toml"]

[font]
size = 13

[font.bold_italic]
family = "Fira Code SemiBold"

[font.italic]
family = "Fira Code Medium"

[font.bold]
style = "SemiBold"

[font.normal]
family = "Fira Code"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Backspace"
mods = "Control"

# Pass <m-:> through to toggle terminal in NeoVim
[[keyboard.bindings]]
chars = "\u001B\u003A"
key = ":"
mods = "Alt|Shift"

# [[keyboard.bindings]]
# action = "ToggleViMode"
# key = "?"
# mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
mode = "Vi"
key = "q"


[shell]
# I start with tmux using the command `alacritty -e usr/bin/tmux`
# program = "/bin/tmux"
program = "/bin/fish"

[window]
decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 110
lines = 45

[window.padding]
x = 6
y = 6
