import = ["/home/ammar/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 12.5

[font.bold_italic]
style = "Bold"

[font.italic]
style = "SemiBold"

[font.normal]
family = "Fira Code"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Backspace"
mods = "Control"


[shell]
# I start with tmux using the command `alacritty -e usr/bin/tmux`
# program = "/bin/tmux"
program = "/bin/fish"

[window]
decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 110
lines = 45

[window.padding]
x = 3
y = 3
