[font]
size = 13
normal = { family = "Fira Code", style = "Medium" }
bold = { style = "SemiBold" }

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Backspace"
mods = "Control"

# Pass <m-:> through to toggle terminal in NeoVim
[[keyboard.bindings]]
chars = "\u001B\u003A"
key = ":"
mods = "Alt|Shift"

# [[keyboard.bindings]]
# action = "ToggleViMode"
# key = "?"
# mods = "Alt|Shift"

# HACK: TMUX doesn't handle <C-;>, so I remapped it to <C-\> 
# So I can use the keybinding to map the toggle terminal in neovim.
[[keyboard.bindings]]
chars = "\u001c"
key = ";"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
mode = "Vi"
key = "q"


[terminal.shell]
# I start with tmux using the command `alacritty -e usr/bin/tmux`
# program = "/bin/tmux"
program = "/bin/fish"

[window]
decorations = "none"
opacity = 0.96
startup_mode = "Maximized"
dynamic_padding = true

[window.dimensions]
columns = 110
lines = 45

[window.padding]
x = 6
y = 6

[general]
import = ["/home/ammar/.config/alacritty/gruvbox_dark.toml"]

[terminal]
