theme = "catppuccin_mocha_no_italic"

[editor]
line-number = "relative"
idle-timeout = 200
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]

[editor.lsp]
auto-signature-help = false

[keys.normal]
C-s = ":w"
C-y = ":fmt"
C-q = ":bclose"
C-space = "signature_help"

[keys.insert]
C-s = ":w"
C-y = ":fmt"
C-q = "collapse_selection"
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"
C-space = "signature_help"

[keys.select]
C-s = ":w"
C-y = ":fmt"

[keys.normal.space]
q = ":quit"
