theme = "catppuccin_mocha"
# theme = "catppuccin_mocha_no_italic"

[editor]
line-number = "relative"
idle-timeout = 200
bufferline = "always"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]
left = ["mode", "spinner", "version-control", "file-name"]

# [editor.lsp]
# auto-signature-help = false
# display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
# C-s = ":w"
C-y = ":fmt"
C-q = ":bclose"
C-space = "signature_help"
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
# V = ["goto_first_nonwhitespace", "extend_to_line_end"]
V = ["extend_line", "trim_selections"]
x = "extend_line"
'{' = "select_prev_sibling"
'}' = "select_next_sibling"
D = ["move_prev_word_start" ,"move_next_word_end", "search_selection", "select_mode"]
A-k = ["extend_line", "delete_selection", "move_line_up", "move_line_up", "paste_after", "collapse_selection"]
A-j = ["extend_line", "delete_selection", "paste_after", "collapse_selection"]

[keys.insert]
# C-s = ":w"
C-y = ":fmt"
C-q = "collapse_selection"
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"
C-space = "signature_help"

[keys.select]
# C-s = ":w"
C-y = ":fmt"
i = ["insert_mode", "collapse_selection"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["search_selection", "select_mode"]

[keys.normal.space]
q = ":quit"
e = ":write"
n = ":set lsp.display-inlay-hints true"
m = ":set lsp.display-inlay-hints false"
