# theme = "catppuccin_mocha"
theme = "gruvbox"
# theme = "catppuccin_mocha_no_italic"

[editor]
line-number = "relative"
idle-timeout = 200
bufferline = "always"
color-modes = true
cursorline = true
scrolloff = 10
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.lsp]
auto-signature-help = false
# display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

# [editor.whitespace.render]
# newline = "all"

# [editor.whitespace.characters]
# # newline = "⏎"
# newline = "↲"

[keys.normal]
C-s = ":w"
C-y = ":fmt"
C-space = "signature_help"
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
# V = ["goto_first_nonwhitespace", "extend_to_line_end"]
V = ["extend_line", "trim_selections"]
x = ["extend_line", "select_mode"]
'{' = "select_prev_sibling"
'}' = "select_next_sibling"
D = ["move_prev_word_start" ,"move_next_word_end", "search_selection", "select_mode"]
# A-k = ["extend_line", "delete_selection", "move_line_up", "move_line_up", "paste_after", "collapse_selection"]
# A-j = ["extend_line", "delete_selection", "paste_after", "collapse_selection"]
C-q = ":buffer-close"
H = ":buffer-previous"
L = ":buffer-next"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"
K = "hover"
A-k = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
A-j = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]

[keys.insert]
C-s = [":w", "normal_mode"]
C-y = ":fmt"
C-q = "collapse_selection"
C-k = "signature_help"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-backspace = "delete_word_backward"
C-l = "normal_mode" 
'C-[' = "normal_mode" 

# # Exit insert mode with `jk` and `jj`
# [keys.insert.j]
# k = "normal_mode"
# j = "normal_mode" 

[keys.select]
C-y = ":fmt"
i = ["insert_mode", "collapse_selection"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["search_selection", "select_mode"]
c = ["trim_selections", "change_selection"]
A-k = ["goto_line_end","extend_line_below",  "delete_selection", "move_line_up", "paste_before", "select_mode"]
A-j = ["goto_line_end","extend_line_below",  "delete_selection", "paste_after", "select_mode" ]

[keys.normal.space]
q = ":quit"
e = ":write"
n = ":toggle-option lsp.display-inlay-hints"
# expermenting: This runs cspell on the changed files and dump the results in a new buffer
# z = [":hnew", ":append-output cspell $(git diff --name-only)"]

